In [2]:
import pandas as pd
import numpy as np

In [12]:
letter = "U"
version = "4_27_24"

In [14]:
#df = pd.read_csv("./images/version1/Labeled/H/Version_4_27_24/ImagesLabels.csv")
df = pd.read_csv(f"../../images/version1/Labeled/{letter}/Version_{version}/ImagesLabels.csv")
df

,annotation_id,annotator,created_at,id,image,label,lead_time,updated_at
0,566,1,2024-04-26T23:44:35.760555Z,537,/data/upload/8/9dc944da-img189.jpg,"[{""x"":79.52,""y"":51.857614678899075,""width"":9.6...",4.087,2024-04-26T23:44:35.760570Z
1,567,1,2024-04-26T23:44:44.029566Z,538,/data/upload/8/c8b7fc79-img188.jpg,"[{""x"":82.08,""y"":20.855779816513756,""width"":11....",8.730,2024-04-26T23:44:51.737439Z
2,568,1,2024-04-26T23:45:04.598157Z,539,/data/upload/8/8621ab37-img187.jpg,"[{""x"":14.24,""y"":14.937247706422015,""width"":12....",7.682,2024-04-26T23:45:04.598190Z
3,569,1,2024-04-26T23:45:12.185062Z,540,/data/upload/8/797f7448-img186.jpg,"[{""x"":8.959999999999999,""y"":44.52990825688073,...",5.087,2024-04-26T23:45:12.185077Z
4,570,1,2024-04-27T01:39:15.414717Z,541,/data/upload/8/1859c8ea-img184.jpg,"[{""x"":42.72,""y"":51.857614678899075,""width"":14....",15.107,2024-04-27T01:39:15.414733Z
...,...,...,...,...,...,...,...,...
136,541,1,2024-04-26T23:36:37.877146Z,674,/data/upload/8/dd5569ff-img7.jpg,"[{""x"":67.36,""y"":36.92036697247706,""width"":9.92...",4.876,2024-04-26T23:36:37.877157Z
137,540,1,2024-04-26T23:36:27.640413Z,675,/data/upload/8/d25b1f7d-img6.jpg,"[{""x"":76.96,""y"":72.4315596330275,""width"":12.64...",18.838,2024-04-26T23:36:31.737116Z
138,539,1,2024-04-26T23:36:11.083196Z,676,/data/upload/8/662af87f-img5.jpg,"[{""x"":42.71999999999999,""y"":75.53174311926605,...",10.265,2024-04-26T23:36:11.083206Z
139,538,1,2024-04-26T23:36:00.015588Z,677,/data/upload/8/47621487-img3.jpg,"[{""x"":24.8,""y"":31.84733944954128,""width"":8.000...",3.234,2024-04-26T23:36:00.015606Z
140,537,1,2024-04-26T23:35:55.895126Z,678,/data/upload/8/6a3089aa-img2.jpg,"[{""x"":51.519999999999996,""y"":42.8388990825688,...",3.392,2024-04-26T23:35:55.895144Z

In [15]:
imageStrs = df["image"]

fileNames = []
fileWidths = []
fileHeights = []
fileX_Min = []
fileY_Min = []
fileX_Max = []
fileY_Max = []

for image in imageStrs:
    imageName = image[image.rfind("/") + 1:]
    imageName = imageName[:imageName.index(".")]
    
    file = open(f"../../images/version1/Labeled/{letter}/Version_{version}/Annotations/{imageName}.xml", "r")
    #file = open(f"./images/version1/Labeled/H/Version_4_26_24/Annotations/{imageName}.xml", "r")
    lines = file.readlines()

    imageNum = imageName[imageName.index("-") + 1:]
    
    imageDim = [dim[dim.index(">") + 1 : dim.rfind("<")] for dim in lines[16:18]]
    width = int(imageDim[0])
    height = int(imageDim[1])
    
    imageBoundBox = [box[box.index(">") + 1 : box.rfind("<")] for box in lines[27:31]]
    x_min = int(imageBoundBox[0])
    y_min = int(imageBoundBox[1])
    x_max = int(imageBoundBox[2])
    y_max = int(imageBoundBox[3])


    fileNames.append(imageName)
    fileWidths.append(width)
    fileHeights.append(height)
    fileX_Min.append(x_min)
    fileY_Min.append(y_min)
    fileX_Max.append(x_max)
    fileY_Max.append(y_max)

In [39]:
df.label[0]

'[{"x":37.23958333333333,"y":71.3302752293578,"width":11.588541666666671,"height":22.018348623853214,"rotation":0,"rectanglelabels":["H"],"original_width":384,"original_height":218}]'

In [40]:
file = open("./images/version1/Labeled/H/Version_4_26_24/Annotations/0a9f66b9-img134.xml", "r")
lines = file.readlines()
lines[3], lines[16:18], lines[27:31]

('<filename>0a9f66b9-img134.jpg</filename>\n',
 ['<width>384</width>\n', '<height>218</height>\n'],
 ['<xmin>231</xmin>\n',
  '<ymin>121</ymin>\n',
  '<xmax>255</xmax>\n',
  '<ymax>143</ymax>\n'])

In [16]:
finalDF = pd.DataFrame({"image" : fileNames, 
              "width" : fileWidths,
              "height" : fileHeights,
              "x_min" : fileX_Min,
              "y_min" : fileY_Min,
              "x_max" : fileX_Max,
              "y_max" : fileY_Max,
              "label" : 2})

finalDF
finalDF.to_csv(f"../../images/version1/Labeled/{letter}/Version_{version}/BB_Images.csv")

In [15]:
full_H = pd.read_csv("../../images/version1/Labeled/H/Version_4_27_24/BB_Images.csv")
full_S = pd.read_csv("../../images/version1/Labeled/S/Version_4_27_24/BB_Images.csv")
full_U = pd.read_csv("../../images/version1/Labeled/U/Version_4_27_24/BB_Images.csv")

In [20]:
full_H.drop("Unnamed: 0", axis=1, inplace=True)
full_S.drop("Unnamed: 0", axis=1, inplace=True)
full_U.drop("Unnamed: 0", axis=1, inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [19]:
full_H

               image  width  height  x_min  y_min  x_max  y_max  label
0      89b7954e-img0    384     218    142    155    186    203      0
1      993c30f1-img1    384     218    139    129    186    183      0
2      99d065ef-img2    384     218    128     31    185     90      0
3      faa3bddb-img3    384     218    123     73    212    182      0
4      131b7e66-img4    384     218     46     64    150    170      0
..               ...    ...     ...    ...    ...    ...    ...    ...
208  54e35d3f-img198    384     218    149    165    182    200      0
209  4ccb529e-img196    384     218    269    138    297    166      0
210  84b291b9-img195    384     218    208    142    238    171      0
211  bf36bc2c-img194    384     218    191    143    218    170      0
212  591bc3d6-img193    384     218    188    126    208    148      0

[213 rows x 8 columns]

In [7]:
full_S

               image  width  height  x_min  y_min  x_max  y_max  label
0    79167d71-img233    384     218    194    115    230    148      1
1    9005753b-img232    384     218    197    111    229    144      1
2    6d682278-img231    384     218    191    114    226    148      1
3    e5890f8c-img230    384     218    206    126    234    157      1
4    5f7b812d-img229    384     218    178    113    203    138      1
..               ...    ...     ...    ...    ...    ...    ...    ...
157    24f19b48-img7    384     218    278    142    334    199      1
158    90b7aa77-img6    384     218    288     19    337     77      1
159    9c26deb6-img5    384     218    118     17    162     64      1
160    3eb51674-img4    384     218     65     71    119    133      1
161    a8591cd8-img3    384     218    175     90    222    144      1

[162 rows x 8 columns]

In [8]:
full_U

               image  width  height  x_min  y_min  x_max  y_max  label
0    9dc944da-img189    384     218    305    113    341    154      2
1    c8b7fc79-img188    384     218    315     45    359     90      2
2    8621ab37-img187    384     218     54     32    103     86      2
3    797f7448-img186    384     218     34     97     82    148      2
4    1859c8ea-img184    384     218    164    113    218    169      2
..               ...    ...     ...    ...    ...    ...    ...    ...
136    dd5569ff-img7    384     218    258     80    296    123      2
137    d25b1f7d-img6    384     218    295    157    343    205      2
138    662af87f-img5    384     218    164    164    210    213      2
139    47621487-img3    384     218     95     69    125    102      2
140    6a3089aa-img2    384     218    197     93    232    128      2

[141 rows x 8 columns]

In [29]:
thing = pd.DataFrame({"23" : [123242]})

In [30]:
thing

       23
0  123242

In [21]:
df32 = pd.concat([full_H, full_S, full_U])
df32.to_csv("../../images/version1/Labeled/Full/Version_4_27_24/Full_BB_Images.csv")

In [10]:
df32

             image  width  height  x_min  y_min  x_max  y_max  label
0    89b7954e-img0    384     218    142    155    186    203      0
1    993c30f1-img1    384     218    139    129    186    183      0
2    99d065ef-img2    384     218    128     31    185     90      0
3    faa3bddb-img3    384     218    123     73    212    182      0
4    131b7e66-img4    384     218     46     64    150    170      0
..             ...    ...     ...    ...    ...    ...    ...    ...
136  dd5569ff-img7    384     218    258     80    296    123      2
137  d25b1f7d-img6    384     218    295    157    343    205      2
138  662af87f-img5    384     218    164    164    210    213      2
139  47621487-img3    384     218     95     69    125    102      2
140  6a3089aa-img2    384     218    197     93    232    128      2

[516 rows x 8 columns]

In [45]:
full_U.shape

(141, 8)